# Generated by Django 2.0.7 on 2018-07-29 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_remove_price_itemgroupid'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='displayName',
            field=models.CharField(default='', max_length=64),
        ),
    ]
