# Generated by Django 2.0.7 on 2018-08-01 23:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=64)),
                ('quantity', models.IntegerField()),
                ('cartItem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.Price')),
            ],
        ),
    ]
